name: biblio

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: ajc/biblio-mysql
    container_name: biblio-mysql

    networks:
      - biblio

    environment:
      MYSQL_DATABASE: biblio
      MYSQL_ROOT_PASSWORD: root

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 3s
      retries: 10
      interval: 5s

  java:
    build: .
    image: ajc/biblio

    container_name: biblio-java

    networks:
      - biblio

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/biblio
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    depends_on:
      mysql:
        condition: service_healthy

networks:
  biblio:
    name: biblio