# Configuration JPA
quarkus.datasource.jdbc.url = jdbc:mysql://mysql:3306/biblio
quarkus.datasource.username = root
quarkus.datasource.password = root

quarkus.hibernate-orm.database.generation = update
quarkus.hibernate-orm.log.sql = true

# Configuration accès
quarkus.http.auth.permission.auth.paths = /api/auth
quarkus.http.auth.permission.auth.policy = permit

quarkus.http.auth.permission.api.paths = /*
quarkus.http.auth.permission.api.policy = authenticated

# - Configuration JWT -
quarkus.smallrye-jwt.enabled = true

# La clé privée pour signer les jetons
smallrye.jwt.sign.key.location = classpath:privateKey.pem
smallrye.jwt.new-token.lifespan = 3600

# Pour valider le jeton
mp.jwt.verify.issuer = formation-quarkus-issuer
mp.jwt.verify.publickey.location = classpath:publicKey.pem
